### ISSUE TITLE
 https无法连接

### ISSUE THREAD

**Issue by SecureKaiser** [Ciyfly/woodpecker#2]
https无法连接

**Comment by Ciyfly** [comment]
已修改，可以试试 感谢师傅反馈

**Comment by SecureKaiser** [comment]
![image](https://github.com/Ciyfly/woodpecker/assets/104421343/6607e64b-5655-40ee-a606-d4b71bcc9bae)
还是不行

**Comment by Ciyfly** [comment]
已修改 是域名的时候我判断目标是否可以访问的时候 直接用host了 对于80 443 没做支持 现在应该可以了
感谢反馈

**Comment by SecureKaiser** [comment]
好的感谢师傅
